### ISSUE TITLE
希望可以支持转发xorg   

### ISSUE THREAD

**Issue by zhenruyan** [trzsz/tsshd#1]
ssh 转发X 和转发端口 的重度用户

ssh转发端口还能凑合

但是转发x 延迟一高  gui界面就容易崩

**Comment by lonnywong** [comment]
`-X` `-Y` `ForwardX11` ? 有些复杂，等我有空时研究研究。

**Comment by lonnywong** [comment]
已支持，tssh 和 tsshd 安装最新的版本，即可使用。
