### ISSUE TITLE
如果开启UdpMode，防火墙得开放61000~62000之间的所有UDP端口？

### ISSUE THREAD

**Issue by bagualing** [trzsz/tsshd#2]
如果开启UdpMode，防火墙得开放61000~62000之间的所有UDP端口？

**Comment by lonnywong** [comment]
是的，现在随机的。

**Comment by lonnywong** [comment]
等我有空了，再加个指定端口范围的参数，允许用户自己设置。

**Comment by lonnywong** [comment]
已支持自定义端口。

在 `tsshd v0.1.3` 发布前，可以这样安装 `go install github.com/trzsz/tsshd/cmd/tsshd@main`，安装的路径在 `~/go/bin` 。

在 `tssh v0.1.22` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `C:\Users\your_name\go\bin\` 。
