### ISSUE TITLE
进程被杀死时通知客户端关闭连接

### ISSUE THREAD

**Issue by Hentioe** [trzsz/tsshd#3]
目前的 tsshd 好像没有这方面的设计。

如果执行 pkill tsshd（给进程发送终止信号）或 reboot（重启系统），客户端那边就直接卡死了。经过连续几分钟的心跳包超时后，客户端才主动关闭连接。

这个机制不一定能 100% 保证客户端收到断开连接的消息，但我想还有必要这么做，能提高体验。

**Comment by lonnywong** [comment]
现在是有这个功能的，默认 tsshd 被 kill 了之后，客户端会在 100 秒左右自动退出。可通过配置 `UdpAliveTimeout` 进行调整：

```
Host test
    #!! UdpAliveTimeout 50  # 单位是秒
```

**Comment by Hentioe** [comment]
是的 所以你打算实现这个吗

**Comment by lonnywong** [comment]
我周末实现一下。

**Comment by Hentioe** [comment]
这部分我已经实现了 近期我可能就会开 pr 不过我对 Go 语言不太熟悉 你可能要 rebase 一下

**Comment by lonnywong** [comment]
不知你是如何做的，按理说几行代码就可以了。
